name: Deploy NodeJS Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Pull latest changes
      run: |
        cd /var/www/HelpdeskEksamen
        git pull origin main
        echo "Pull latest changes completed successfully at $(date)"
        
    - name: Reload PM2
      run: |
        sudo pm2 reload HelpdeskEksamen
        echo "Reload of PM2 completed successfully at $(date)"
        
    - name: Verify deployment
      run: |
        echo "Deployment completed successfully at $(date)"
